/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.15
 * Generated at: 2018-08-09 12:56:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jobhunter.components.*;

public final class CreateProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.jobhunter.components");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chunks/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("theTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Create your profile", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  <form method=\"POST\" action=\"/JobHunter/home\">\r\n");
      out.write("  \t  <h3>Personal Details</h3>\r\n");
      out.write("\t  <div class=\"well\">\t\r\n");
      out.write("\t\t  <div class=\"pull-right\">\r\n");
      out.write("\t\t \t<button type=\"submit\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("\t\t       <span class=\"glyphicon glyphicon-ok\"></span> Save \r\n");
      out.write("\t\t     </button>\r\n");
      out.write("\t\t \t<button type=\"button\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("\t\t       <span class=\"glyphicon glyphicon-remove\"></span> Cancel \r\n");
      out.write("\t\t     </button>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t \r\n");
      out.write("  \r\n");
      out.write("\t    <br>\r\n");
      out.write("\t    <label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account.emailAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("\t\t<label for=\"firstName\">First Name</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"firstName\">\r\n");
      out.write("\t\t<label for=\"middleName\">Middle Name</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"middleName\" name=\"middleName\">\r\n");
      out.write("\t\t<label for=\"lastName\">Last Name</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label for=\"jobTitle\">Job Title</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"jobTitle\" name=\"jobTitle\">\r\n");
      out.write("\t\t<label for=\"address\">Address</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"\"address\" name=\"address\">\r\n");
      out.write("\t\t<label for=\"mobile\">Mobile Number</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"\"mobile\" name=\"mobile\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <h3>Job Preference</h3>\r\n");
      out.write("\t  <div class=\"well\">\t    \r\n");
      out.write("\t    <br>\r\n");
      out.write("\t    \r\n");
      out.write("\t\t<label for=\"desiredJobTitle\">Desired Job Title</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"desiredJobTitle\" name=\"desiredJobTitle\">\r\n");
      out.write("\t\t<label for=\"jobType\">Job Type (select one):</label>\r\n");
      out.write("\t\t<select class=\"form-control\" id=\"jobType\" name=\"jobType\">\r\n");
      out.write("\t\t  <option>Entry</option>\r\n");
      out.write("\t\t  <option>Full Time</option>\r\n");
      out.write("\t\t  <option>Part Time</option>\r\n");
      out.write("\t\t  <option>Contract</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t <h3>Work Experience</h3>\r\n");
      out.write("\t  <div class=\"well\">\r\n");
      out.write("\r\n");
      out.write("\t\t<label for=\"company\">Company Name</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"company\" name=\"company\">\r\n");
      out.write("\t\t<label for=\"jobTitle\">Job Title</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"jobTitle\" name=\"jobTitle\">\r\n");
      out.write("\t    <label for=\"fromWorkExperience\">From</label>\r\n");
      out.write("\t\t<select class=\"form-control\" id=\"fromWorkExperience\" name=\"fromWorkExperience\">\r\n");
      out.write("\t\t  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chunks/year_list.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<label for=\"toWorkExperience\">To</label>\r\n");
      out.write("\t\t<select class=\"form-control\" id=\"toWorkExperience\" name=\"toWorkExperience\">\r\n");
      out.write("\t\t  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chunks/year_list.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label for=\"descriptionWorkExperience\">Description:</label>\r\n");
      out.write("        <textarea class=\"form-control\" rows=\"5\" id=\"descriptionWorkExperience\" name=\"descriptionWorkExperience\"></textarea>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <div class=\"pull-right\">\r\n");
      out.write("\t    \t<button type=\"button\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("\t          <span class=\"glyphicon glyphicon-plus\"></span> Add \r\n");
      out.write("\t        </button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <br>\r\n");
      out.write("\t    \r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <h3>Education</h3>\r\n");
      out.write("\t  <div class=\"well\">\r\n");
      out.write("\t  \t\t    \r\n");
      out.write("\t\t<label for=\"company\">School Name</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"company\" name=\"company\">\r\n");
      out.write("\t\t<label for=\"degree\">Degree</label>\r\n");
      out.write("\t\t<input type=\"text\" class=\"form-control\" id=\"\"degree\"\" name=\"\"degree\"\">\r\n");
      out.write("\t    <label for=\"fromEducation\">From</label>\r\n");
      out.write("\t\t<select class=\"form-control\" id=\"fromEducation\" name=\"fromEducation\">\r\n");
      out.write("\t\t  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chunks/year_list.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<label for=\"toEducation\">From</label>\r\n");
      out.write("\t\t<select class=\"form-control\" id=\"toEducation\" name=\"toEducation\">\r\n");
      out.write("\t\t  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chunks/year_list.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<label for=\"descriptionEducation\">Description:</label>\r\n");
      out.write("        <textarea class=\"form-control\" rows=\"5\" id=\"descriptionEducation\" name=\"descriptionEducation\"></textarea>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <div class=\"pull-right\">\r\n");
      out.write("\t    \t<button type=\"button\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("\t          <span class=\"glyphicon glyphicon-plus\"></span> Add \r\n");
      out.write("\t        </button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <br>\r\n");
      out.write("\t    \r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <h3>Education</h3>\r\n");
      out.write("\t  <div class=\"well\">\r\n");
      out.write("\t  \t    \r\n");
      out.write("\t\t<label for=\"skills\">Skills (Separated in comma):</label>\r\n");
      out.write("        <textarea class=\"form-control\" rows=\"5\" id=\"skills\" name=\"skills\" placeholder=\"separated in comma\"></textarea>\r\n");
      out.write("\t    \r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \t<div class=\"pull-right\">\r\n");
      out.write("\t    \t<button type=\"submit\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("\t          <span class=\"glyphicon glyphicon-ok\"></span> Save \r\n");
      out.write("\t        </button>\r\n");
      out.write("\t    \t<button type=\"button\" class=\"btn btn-default btn-sm\">\r\n");
      out.write("\t          <span class=\"glyphicon glyphicon-remove\"></span> Cancel \r\n");
      out.write("\t        </button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <br>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
